### PR TITLE
Add tum facade dataset

### PR DESCRIPTION
**Pull request by ThomasFroech**
added dataset classes for the TUM-Facade dataset (https://github.com/OloOcki/tum-facade ) and updated the init file

- - -
This change is [Reviewable](https://reviewable.io/reviews/isl-org/Open3D-ML/613)

### CODE REVIEW

**Review by ssheorey — COMMENTED** [review]
Hi @ThomasFroech this PR modifies the API for `update_probs()`. Can you explain the reasoning behind that?

**Comment by ssheorey** [comment]
Hi @ThomasFroech  can you add a readme.md for the dataset with this information:

Website:
Download:
Data License:
Leaderboard:
Citation:

**Comment by ThomasFroech** [comment]
Hi @ssheorey,

> Hi @ThomasFroech can you add a readme.md for the dataset with this information:

There is a README.md available in the original GitHub repo (https://github.com/OloOcki/tum-facade).  I think that all important information is there. While the data can be downloaded from that source, I would recommend obtaining it from this location instead. Here, the data is organized into training, validation, and testing sets. The data structre is described in the small README.txt that is available, there: 

https://tumde-my.sharepoint.com/:f:/g/personal/olaf_wysocki_tum_de/EjA8B_KGDyFEulRzmq-CG1QBBL4dZ7z5PoHeI8zMD0JxIQ?e=9MrMcl

> Hi @ThomasFroech this PR modifies the API for `update_probs()`. Can you explain the reasoning behind that?

I'm sorry, but I'm not entirely sure about the specific point you're referring to. Would you kindly provide me with a hint or more details to help me better understand?

**Comment by ThomasFroech** [comment]
@ssheorey 

> Hi @ThomasFroech this PR modifies the API for `update_probs()`. Can you explain the reasoning behind that?

My intention was solely to add the `tumfacade.py` file and make corresponding adjustments to the `__init__.py` file. I did not have any intention to alter or adapt any other components.

**Review by ssheorey — APPROVED** [review]
Hi @ThomasFroech sorry about the confusion about the `update_probs()` - that change came from an unrelated commit.

- Added documentation based on info provided.
- Fixed style.

**Pull request merged**
