### PR TITLE
Add NuScenes lidar semantic segmentation support

### PR DESCRIPTION
**Pull request by ajinkyakhoche**
- Modified preprocessing and dataset script to add lidarseg info, new label dict (including both foreground and background classes) and a method to load semantic labels. 
- Modified visualizer to load and show labels correctly
- Added a config to train randlanet on Nuscenes
ref: [lidarseg](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/instructions_lidarseg.md)

Thanks to [mmdetection3d](https://github.com/open-mmlab/mmdetection3d) project 

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/365)

### CODE REVIEW

**Comment by sanskar107** [comment]
@ajinkyakhoche Thanks for all your contributions. Would you be interested in contributing further ?

**Comment by ajinkyakhoche** [comment]
@sanskar107 Yes. what do you propose?

**Comment by ajinkyakhoche** [comment]
@sanskar107 I just noticed that `label_to_names` (and hence `num_labels`) will be different depending on task at hand: 
- 11 labels including 'ignore' for 3D object detection and
- 32 labels including 'noise' for 3D semantic segmentation. 

If so, I probably shouldn't remove the original `label_to_names` on [this commit](https://github.com/isl-org/Open3D-ML/pull/365/files?file-filters%5B%5D=.py#diff-afa2fd06f350c6e1e77adb1caab592e6d5405596647d6f6765a20546dba2aa8eL89)

How can this be resolved? Should another class (eg NuScenesSeg) be created (mmdetection3d does something similar, like [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/scannet_dataset.py))? Or perhaps another list `label_to_names_semantic` be added to same class?

**Comment by sanskar107** [comment]
@ajinkyakhoche We can add another argument to the dataset class to determine the task.
something like `task="SemanticSegmentation# or ObjectDetection"`.

**Pull request closed without merging**
