### PR TITLE
Distributed training with PyTorch: PointPillars on Waymo

### PR DESCRIPTION
**Pull request by sanskar107**
Added support for distributed training for PyTorch `ObjectDetection` pipeine.

- [x] Modify launch script to spawn multiple process for multi-gpu training.
- [x] Update Object Detection Pipeline to support multiple gpus.
- [x] Train PointPillars on large scale datasets like Waymo.
- [ ] Train PointRCNN on Waymo.
- [ ] Update Semantic Segmentation pipeiine to support multi-gpu. (Update RandLANet and KPConv to avoid using samplers in dataloaders)
- [ ] Train Semantic Segmentation models.

Some Results:
[Vehicle] green : ground truth
[Vehicle] orange: prediction
image
image

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/353)

### CODE REVIEW

**Review by ssheorey — COMMENTED** [review]
Can you rename this PR to something like "Distributed training with PyTorch: PointPillars on Waymo". For PointRCNN, we will have a separate PR, right?

> Reviewed 1 of 10 files at r8.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/353#-:-MwiNp8DBKmLRFLNA20n:b-wlmzjk)* status: 1 of 17 files reviewed, 23 unresolved discussions (waiting on @sanskar107 and @ssheorey)

___
*[ml3d/configs/pointpillars_waymo.yml, line 109 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwiNP1IBvZuVBia1V_S:-MwiNP1IBvZuVBia1V_T:bpgrcyq) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/configs/pointpillars_waymo.yml#L109)):*
> ```YAML
>   difficulties: [0, 1, 2]
>   summary:
>     record_for: [train, valid]
> ```

Set to empty before merge.
___
*[ml3d/datasets/waymo.py, line 3 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwiOMv18JjwTiWvOTm1:-MwiOMv18JjwTiWvOTm2:bu1iain) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/datasets/waymo.py#L3)):*
> ```Python
> import numpy as np
> import os, argparse, pickle, sys
> from os.path import exists, join, isfile, dirname, abspath, split
> ```

nit: avoid unused imports, multiple imports on one lines (see lgtm messages).
___
*[ml3d/datasets/waymo.py, line 94 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwiR8hB0_7WBDEaLPMY:-MwiR8hC36A6_zCm_0zn:b-g9h8tg) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/datasets/waymo.py#L94)):*
> ```Python
> 
>         Returns:
>             A data object with lidar information.
> ```

Mention return data format. e.g. each row is `XYZRGB`?
___
*[ml3d/datasets/waymo.py, line 96 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwiRwSl5SHbuPimcuyY:-MwiRwSl5SHbuPimcuyZ:bz550sc) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/datasets/waymo.py#L96)):*
> ```Python
>             A data object with lidar information.
>         """
>         assert Path(path).exists()
> ```

Not necessary. `np.fromfile()` will complain if path is incorrect.
___
*[ml3d/datasets/waymo.py, line 105 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwiSAHp7ZASB_7V-8HB:-MwiSAHp7ZASB_7V-8HC:b-xzdv26) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/datasets/waymo.py#L105)):*
> ```Python
> 
>         Returns:
>             The data objects with bound boxes information.
> ```

bounding boxes
___
*[ml3d/datasets/waymo.py, line 135 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwiSUxb2htfrebaTCop:-MwiSUxb2htfrebaTCoq:b-95cgxq) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/datasets/waymo.py#L135)):*
> ```Python
>             The camera and the camera image used in calibration.
>         """
>         assert Path(path).exists()
> ```

Not necessary. `open()` will complain if path is incorrect.
___
*[ml3d/datasets/waymo.py, line 140 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwiTWyeEueIO_m1hubc:-MwiTWyeEueIO_m1hubd:b-tsv0rl) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/datasets/waymo.py#L140)):*
> ```Python
>             lines = f.readlines()
>         obj = lines[0].strip().split(' ')[1:]
>         P0 = np.array(obj, dtype=np.float32)
> ```

Name unused variables as `unused_P0`, etc.  Also P1, P3, P4.
___
*[ml3d/datasets/waymo.py, line 223 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwiVTvVA4k7VEsO3c_A:-MwiVTvVA4k7VEsO3c_B:b-gttqo9) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/datasets/waymo.py#L223)):*
> ```Python
>                 attribute is stored; else, returns false.
>         """
>         pass
> ```

Is this unimplemented? If we want to implement this later, `return false` would be better since a return value is expected. Also print warning / `NotImplementedError()` as appropriate.
___
*[ml3d/datasets/waymo.py, line 232 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwiVjVXBiqcaZWnmdDW:-MwiVjVY7k_haT2bjIUX:b-6t8skn) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/datasets/waymo.py#L232)):*
> ```Python
>             attr: The attributes that correspond to the outputs passed in results.
>         """
>         pass
> ```

Print warning / `NotImplementedError()`
___
*[ml3d/datasets/waymo.py, line 282 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwiWCCn88ZgY0mK2rKK:-MwiWCCn88ZgY0mK2rKL:b-8citvt) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/datasets/waymo.py#L282)):*
> ```Python
> 
>     def __init__(self, center, size, label, calib):
>         confidence = float(label[15]) if label.__len__() == 16 else -1.0
> ```

Are there 2 different formats? Add comment explaining this.
nit: Add "extra" data (confidence, occlusion, etc.) explanation to docstring.
___
*[scripts/run_pipeline.py, line 232 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwiXN_2ABaami5JWpWz:-MwiXN_2ABaami5JWpX-:b-vpif2t) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/run_pipeline.py#L232)):*
> ```Python
>     )
> 
>     multiprocessing.set_start_method('spawn')
> ```

`forkserver` is faster than `spawn` and should be preferred in Linux. Does that cause any problems? Also, we probably want to change the default method only in Linux so check OS.

**Review by ssheorey — CHANGES_REQUESTED** [review]
We should add DDP on CPUs in a future PR.

> Reviewed 6 of 11 files at r5, 4 of 10 files at r8, 1 of 1 files at r9, 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/353#-:-MwjJ7FT-8xu6A1Y3wkX:bjo33ie)* status: 13 of 17 files reviewed, 45 unresolved discussions (waiting on @sanskar107 and @ssheorey)

___
*[ml3d/torch/pipelines/base_pipeline.py, line 26 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjGr2lB4tnD_s72GrL:-MwjGr2lB4tnD_s72GrM:bsuyjjn) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/torch/pipelines/base_pipeline.py#L26)):*
> ```Python
>             model: A network model.
>             dataset: A dataset, or None for inference model.
>             device: 'gpu' or 'cpu'.
> ```

'cuda' or 'cpu'
___
*[ml3d/torch/pipelines/base_pipeline.py, line 63 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjHPIYDFv8QlmQKsFH:-MwjHPIYDFv8QlmQKsFI:b-m5mr2l) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/torch/pipelines/base_pipeline.py#L63)):*
> ```Python
>             if distributed:
>                 raise ValueError(
>                     "Distributed training is ON, but CUDA not available.")
> ```

Distributed training on CPUs is supported by PyTorch. If there is a blocking issue, we can raise `NotImplementedError()` here and address it in a future PR. 
___
*[ml3d/torch/pipelines/dataparallel.py, line 1 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjLJAe2iypglwD0I6E:-MwjLJAe2iypglwD0I6F:bzcib9y) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/torch/pipelines/dataparallel.py#L1)):*
> ```Python
> import torch
> ```

Is this file still being used?



_Code quote:_
```Python
CustomDataParall
```
___
*[ml3d/torch/pipelines/object_detection.py, line 180 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjIX2p7f2go0SVgXsE:-MwjIX2p7f2go0SVgXsF:b-k3kqtb) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/torch/pipelines/object_detection.py#L180)):*
> ```Python
>                                   sampler=valid_sampler)
>         # worker_init_fn=lambda x: np.random.seed(x + np.uint32(
>         #     torch.utils.data.get_worker_info().seed)))
> ```

Remove comment if not needed.
___
*[ml3d/torch/pipelines/object_detection.py, line 366 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjKjtIDTTBGQS1R_1B:-MwjKjtIDTTBGQS1R_1C:b-xgqwwz) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/torch/pipelines/object_detection.py#L366)):*
> ```Python
>                     loss = model.module.get_loss(results, data)
>                 else:
>                     loss = model.get_loss(results, data)
> ```

Ideally, we want to avoid this `if (distributed): self.module.* else: self.*` code pattern. Is it possible to use wrapping or inheritance to use `model.get_loss()` even in distributed mode?



_Code quote:_
```Python
                if self.distributed:
                    loss = model.module.get_loss(results, data)
                else:
                    loss = model.get_loss(results, data)
```
___
*[ml3d/torch/pipelines/object_detection.py, line 374 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjMl0k3FGuSGNWNFJ1:-MwjMl0k3FGuSGNWNFJ2:b-8ygo3p) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/torch/pipelines/object_detection.py#L374)):*
> ```Python
>                     if model.module.cfg.get('grad_clip_norm', -1) > 0:
>                         torch.nn.utils.clip_grad_value_(
>                             model.module.parameters(),
> ```

See above. Avoid `model.module.*`
___
*[ml3d/torch/pipelines/object_detection.py, line 387 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjMdbyC0R7-O1wQgZw:-MwjMdbyC0R7-O1wQgZx:b-8ygo3p) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/ml3d/torch/pipelines/object_detection.py#L387)):*
> ```Python
>                     if self.distributed:
>                         boxes = model.module.inference_end(results, data)
>                     else:
> ```

See above. Avoid `model.module.*`
___
*[scripts/collect_bboxes.py, line 5 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjNQ0A1RhmfFvVR6Ao:-MwjNQ0A1RhmfFvVR6Ap:bz7tnv0) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/collect_bboxes.py#L5)):*
> ```Python
> import argparse
> import pickle
> import random
> ```

Avoid random. Stick to one of numpy.rng or torch.random for reproducibility.
___
*[scripts/collect_bboxes.py, line 99 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjNs7h8LID33cE3uOK:-MwjNs7i6GJCe_UUPKaf:br08sgx) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/collect_bboxes.py#L99)):*
> ```Python
> 
>     query_pc = range(len(train)) if max_pc >= len(train) else random.sample(
>         range(len(train)), max_pc)
> ```

Use the NumPy RNG.
___
*[scripts/preprocess_waymo.py, line 14 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjOVCZ-EfQ0jLQjELz:-MwjOVCZ-EfQ0jLQjEM-:b-leibnm) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/preprocess_waymo.py#L14)):*
> ```Python
> from os.path import join, exists, dirname, abspath
> from os import makedirs
> import random
> ```

Use NumPy RNG everywhere.
___
*[scripts/preprocess_waymo.py, line 60 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjR9i-9TGvj3Y9GoQN:-MwjR9i-9TGvj3Y9GoQO:b-rwzl0y) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/preprocess_waymo.py#L60)):*
> ```Python
>     """Waymo to KITTI converter.
> 
>     This class converts tfrecord files from Waymo dataset to KITTI format.
> ```

Can you describe KITTI format here as well, so users don't have to refer to the KITTI code.
Also, add reference to Waymo document / example code explaining the pre-processing (if available).
Add information on tensor shapes and formats, as appropriate (e.g. lidar is (N,6) with each row X, Y, Z, intensity, elongation, timestamp)
___
*[scripts/preprocess_waymo.py, line 140 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjPqUK8hydyLrJb5Ra:-MwjPqUK8hydyLrJb5Rb:b-s5y5h9) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/preprocess_waymo.py#L140)):*
> ```Python
>                     frame.context.stats.location
>                     not in self.selected_waymo_locations):
>                 print("continue")
> ```

Remove if debugging code.



_Code quote:_
```Python
print("continue")
```
___
*[scripts/preprocess_waymo.py, line 197 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjQFK72TEEEqBcfVj2:-MwjQFK72TEEEqBcfVj3:b-5hg4kb) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/preprocess_waymo.py#L197)):*
> ```Python
> 
>         # all camera ids are saved as id-1 in the result because
>         # camera 0 is unknown in the proto
> ```

Document this (and any other) data modification in the class docstring.



_Code quote:_
```Python
        # all camera ids are saved as id-1 in the result because
        # camera 0 is unknown in the proto
```
___
*[scripts/preprocess_waymo.py, line 211 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjQkwB3Bu8FqZoiYvD:-MwjQkwB3Bu8FqZoiYvE:b-cyxc5y) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/preprocess_waymo.py#L211)):*
> ```Python
>                 'w+') as fp_calib:
>             fp_calib.write(calib_context)
>             fp_calib.close()
> ```

`close()` is unnecessary with context manager.
___
*[scripts/preprocess_waymo.py, line 229 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjRgHp6pjozEpF0b0p:-MwjRgHp6pjozEpF0b0q:b-470v0g) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/preprocess_waymo.py#L229)):*
> ```Python
>             name = labels.name
>             for label in labels.labels:
>                 # TODO: need a workaround as bbox may not belong to front cam
> ```

Is this resolved now?
___
*[scripts/preprocess_waymo.py, line 259 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjRQnr16DUfgbyQhRo:-MwjRQnr16DUfgbyQhRp:bkvuv60) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/preprocess_waymo.py#L259)):*
> ```Python
> 
>             # if self.filter_empty_3dboxes and obj.num_lidar_points_in_box < 1:
>             #     continue
> ```

Remove commented code.



_Code quote:_
```Python
            # if self.filter_empty_3dboxes and obj.num_lidar_points_in_box < 1:
            #     continue
```
___
*[scripts/preprocess_waymo.py, line 272 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjRxfdC6U9aczpA7Ci:-MwjRxfdC6U9aczpA7Cj:bz7j2l6) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/preprocess_waymo.py#L272)):*
> ```Python
>             # pt_ref = self.T_velo_to_front_cam @ \
>             #     np.array([x, y, z, 1]).reshape((4, 1))
>             # x, y, z, _ = pt_ref.flatten().tolist()
> ```

Remove commented code if not required any more.



_Code quote:_
```Python
            # # project bounding box to the virtual reference frame
            # pt_ref = self.T_velo_to_front_cam @ \
            #     np.array([x, y, z, 1]).reshape((4, 1))
            # x, y, z, _ = pt_ref.flatten().tolist()
```
___
*[scripts/preprocess_waymo.py, line 341 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjTKJ53dHXXfJl66cc:-MwjTKJ53dHXXfJl66cd:bf1wlxo) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/preprocess_waymo.py#L341)):*
> ```Python
>         timestamp = frame.timestamp_micros * np.ones_like(intensity)
> 
>         # concatenate x,y,z, intensity, elongation, timestamp (6-dim)
> ```

Add this to docstring.
___
*[scripts/preprocess_waymo.py, line 364 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjU6H46zbezkkVhMJ0:-MwjU6H46zbezkkVhMJ1:b-awybq5) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/preprocess_waymo.py#L364)):*
> ```Python
>         frame_pose = tf.convert_to_tensor(
>             value=np.reshape(np.array(frame.pose.transform), [4, 4]))
>         # [H, W, 6]
> ```

Add input / output shape info to docstring
___
*[scripts/preprocess_waymo.py, line 368 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjUDpkDsMg4nEfsrGI:-MwjUDpkDsMg4nEfsrGJ:b-awybq5) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/preprocess_waymo.py#L368)):*
> ```Python
>             tf.convert_to_tensor(value=range_image_top_pose.data),
>             range_image_top_pose.shape.dims)
>         # [H, W, 3, 3]
> ```

Add input / output shape info to docstring
___
*[scripts/run_pipeline.py, line 155 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjUU_7EZIknwvWo7tb:-MwjUU_7EZIknwvWo7tc:b9r8xy5) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/run_pipeline.py#L155)):*
> ```Python
>     args.cfg_tb = cfg_tb
>     args.distributed = framework == 'torch' and args.device != 'cpu' and len(
>         args.device_ids) > 1
> ```

future PR: allow distributed with CPUs.
___
*[scripts/run_pipeline.py, line 181 at r10](https://reviewable.io/reviews/isl-org/open3d-ml/353#-MwjWEMBCj6ZEUhwRWdo:-MwjWEMBCj6ZEUhwRWdp:bscqlq2) ([raw file](https://github.com/isl-org/open3d-ml/blob/51a16c376259ab7d4410e4f4590a2a1090b55bb7/scripts/run_pipeline.py#L181)):*
> ```Python
> 
>     # initialize the process group
>     dist.init_process_group("gloo", rank=rank, world_size=world_size)
> ```

Allow configuring host, port and backend in the pipeline config file. Check if these are already set by the user and respect prior settings in that case.

**Review by benjaminum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r8, 5 of 7 files at r11, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/353)* status: 15 of 17 files reviewed, 48 unresolved discussions (waiting on @sanskar107 and @ssheorey)

___
*[`ml3d/datasets/waymo.py` line 101 at r13](https://reviewable.io/reviews/isl-org/open3d-ml/353#-NAnF9Fv7NYG-WHH5UqF:-NAnF9Fv7NYG-WHH5UqG:blib5c7) ([raw file](https://github.com/isl-org/open3d-ml/blob/77c1a0a62adb1e11e397d958c955bd6d8a034355/ml3d/datasets/waymo.py#L101)):*
> ```Python
> 
>     @staticmethod
>     def read_label(path, calib):
> ```

Please add a short description of path and calib or useful information like where to get the inputs, e.g., `calib: Calibration as returned by read_calib()`.
___
*[`ml3d/datasets/waymo.py` line 279 at r13](https://reviewable.io/reviews/isl-org/open3d-ml/353#-NAnGU6b8X6xcoKaOm1E:-NAnGU6cBHBp_PqmBXQV:b-320e4j) ([raw file](https://github.com/isl-org/open3d-ml/blob/77c1a0a62adb1e11e397d958c955bd6d8a034355/ml3d/datasets/waymo.py#L279)):*
> ```Python
>     """
> 
>     def __init__(self, center, size, label, calib):
> ```

Do we need documentation here or is the base class docstring sufficient?
___
*[`ml3d/torch/pipelines/object_detection.py` line 405 at r13](https://reviewable.io/reviews/isl-org/open3d-ml/353#-NAnPx5261RvIgEJX-Oi:-NAnPx5261RvIgEJX-Oj:b-93e0b7) ([raw file](https://github.com/isl-org/open3d-ml/blob/77c1a0a62adb1e11e397d958c955bd6d8a034355/ml3d/torch/pipelines/object_detection.py#L405)):*
> ```Python
> 
>             # --------------------- validation
>             # if rank == 0 and (epoch % cfg.get("validation_freq", 1)) == 0:
> ```

remove old if

**Review by benjaminum — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/353#-:-NC54hA2DDqnX5yGd4tN:bnfp4nl)* status: 11 of 17 files reviewed, 48 unresolved discussions (waiting on @benjaminum, @sanskar107, and @ssheorey)

**Review by ssheorey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/353)* status: 11 of 17 files reviewed, 16 unresolved discussions (waiting on @benjaminum, @sanskar107, and @ssheorey)

**Pull request merged**
