### PR TITLE
TB plugin example and docs

### PR DESCRIPTION
**Pull request by ssheorey**
- markdown + sphinx TB plugin tutorial
- examples for TB plugin
- Move example data to `open3d_downloads`

~~[Merge after PR #405]~~

See [html.zip](https://github.com/isl-org/Open3D-ML/files/7573236/html.zip) for how the tutorial will look in the sphinx docs, and `docs/tensorboard.md` in this PR for how it will look on github.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/415)

### CODE REVIEW

**Review by benjaminum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/415)* status: 0 of 46 files reviewed, 1 unresolved discussion (waiting on @sanskar107 and @ssheorey)

___
*[docs/tensorboard.md, line 106 at r9](https://reviewable.io/reviews/isl-org/open3d-ml/415#-MoZURP-8JeHITmJpjhw:-MoZURP-8JeHITmJpjhx:b-zfbnm1) ([raw file](https://github.com/isl-org/open3d-ml/blob/0593795ef925ba4108bd569f3cf13bbd8220095e/docs/tensorboard.md#L106)):*
> ```Markdown
> 
> ```sh
> python examples/python/visualization/tensorboard_pytorch.py small_scale
> ```

The path should be `examples/python/gui/tensorboard_pytorch.py`. Same for following examples

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/415)* status: 0 of 47 files reviewed, 1 unresolved discussion (waiting on @benjaminum and @sanskar107)

Oops - looked at your comment in Reviewable, where it was out of context and misinterpreted it. Fixed example paths. [Ignore reply below:]
___
*[docs/tensorboard.md, line 106 at r9](https://reviewable.io/reviews/isl-org/open3d-ml/415#-MoZURP-8JeHITmJpjhw:-Mo_sCvgCX7rWwUXeQR1:b-7p5g0o) ([raw file](https://github.com/isl-org/open3d-ml/blob/0593795ef925ba4108bd569f3cf13bbd8220095e/docs/tensorboard.md#L106)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

The path should be `examples/python/gui/tensorboard_pytorch.py`. Same for following examples
</blockquote></details>

Done. Open3D was to indicate the main repo, since this files serves as documentation for both repos. Changed to:
```
The examples described below are available in the
`examples/python/gui/tensorboard_pytorch.py` and
`examples/python/gui/tensorboard_tensorflow.py` files in the Open3D
repository.
```

**Review by benjaminum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/415)* status: 0 of 47 files reviewed, 3 unresolved discussions (waiting on @benjaminum, @sanskar107, and @ssheorey)

___
*[docs/tensorboard.md, line 170 at r14](https://reviewable.io/reviews/isl-org/open3d-ml/415#-Moc_oUc2cbMmHyHVXA_:-Moc_oUc2cbMmHyHVXAa:b-yx9sox) ([raw file](https://github.com/isl-org/open3d-ml/blob/734cb56f0d4734a648de70ef68a3e84ff717b44f/docs/tensorboard.md#L170)):*
> ```Markdown
> 
> ```python
> MODEL_DIR = "examples/test_data/monkey"
> ```

-> `model_dir`
___
*[docs/tensorboard.md, line 180 at r14](https://reviewable.io/reviews/isl-org/open3d-ml/415#-MocdLF_Ag6qKuhqafEG:-MocdLF_Ag6qKuhqafEH:b4zq3g2) ([raw file](https://github.com/isl-org/open3d-ml/blob/734cb56f0d4734a648de70ef68a3e84ff717b44f/docs/tensorboard.md#L180)):*
> ```Markdown
>     "triangle_texture_uvs": model.triangle["texture_uvs"],
>     "triangle_indices": model.triangle["indices"],
>     "material_name": "defaultLit"
> ```

Just a question. Didn't we rename `material_name` to `material`?

**Review by benjaminum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/415)* status: 0 of 47 files reviewed, 4 unresolved discussions (waiting on @benjaminum, @sanskar107, and @ssheorey)

___
*[docs/tensorboard.md, line 345 at r14](https://reviewable.io/reviews/isl-org/open3d-ml/415#-MoebS4uAGYRyRzZZtFf:-MoebS4uAGYRyRzZZtFg:b-k6p6qs) ([raw file](https://github.com/isl-org/open3d-ml/blob/734cb56f0d4734a648de70ef68a3e84ff717b44f/docs/tensorboard.md#L345)):*
> ```Markdown
>     # float, shape (N, 3), or (B, N, 3) for a batch
>     points = np.load(pcd_files[step])
>     # ????
> ```

is this a placeholder?

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/415)* status: 0 of 55 files reviewed, 4 unresolved discussions (waiting on @benjaminum and @sanskar107)

___
*[docs/tensorboard.md, line 170 at r14](https://reviewable.io/reviews/isl-org/open3d-ml/415#-Moc_oUc2cbMmHyHVXA_:-MoizF4U8CV9JdOAbN9N:b-896fix) ([raw file](https://github.com/isl-org/open3d-ml/blob/734cb56f0d4734a648de70ef68a3e84ff717b44f/docs/tensorboard.md#L170)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

-> `model_dir`
</blockquote></details>

Done.
___
*[docs/tensorboard.md, line 180 at r14](https://reviewable.io/reviews/isl-org/open3d-ml/415#-MocdLF_Ag6qKuhqafEG:-MoiuzTrA8b93tt2UNCe:b-7c3puq) ([raw file](https://github.com/isl-org/open3d-ml/blob/734cb56f0d4734a648de70ef68a3e84ff717b44f/docs/tensorboard.md#L180)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Just a question. Didn't we rename `material_name` to `material`?
</blockquote></details>

We have `material` in RPC serialization. But rendering (`open3d.visualization.Material`) uses `material_name`, so we are using `material_name` here in the TB plugin as well. It would be good to use a single term.
___
*[docs/tensorboard.md, line 345 at r14](https://reviewable.io/reviews/isl-org/open3d-ml/415#-MoebS4uAGYRyRzZZtFf:-MoiwEqd342-k_NEX2pa:bxrrc0u) ([raw file](https://github.com/isl-org/open3d-ml/blob/734cb56f0d4734a648de70ef68a3e84ff717b44f/docs/tensorboard.md#L345)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

is this a placeholder?
</blockquote></details>

Yes. Updated. Changed example to use the Dataset class. Also example data is now in `open3d_downloads` and added a utility function to download it automatically if needed.

**Review by sanskar107 — APPROVED** [review]

**Pull request merged**
