### PR TITLE
PyTorch PointPillars - Fix out of bounds pillar coordinates (issue #349)

### PR DESCRIPTION
**Pull request by kylevedder**
Fixed issue #349 by doing pseudo image bounds check and removing out of bounds pillars.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/350)

### CODE REVIEW

**Comment by kylevedder** [comment]
I was able to run a from-scratch training run on KITTI using this change; without this change the training pipeline would intermittently crash.

**Comment by ssheorey** [comment]
@kylevedder Thanks for submitting this PR! Could you resolve conflicts and update the branch?

**Comment by kylevedder** [comment]
Done; I did not know about the style formatted until just now.

**Comment by kylevedder** [comment]
Sorry, I made a mess of my branch because I rebased onto the wrong `master`. I think everything should be fixed now.

**Review by sanskar107 — APPROVED** [review]

**Pull request merged**
