### PR TITLE
Add bounding boxes to Visualizer DataModel

### PR DESCRIPTION
**Pull request by ajinkyakhoche**
- Added `self.bounding_box_data` to Visualizer DataModel. This allows storing/loading bounding boxes alongside the lidar data. This is helpful when inferring object detection on on multiple lidar frames.
- When inferring on single frame, bounding boxes can be passed separately (as before). When inferring on multiple frames, the bounding boxes can be added as a key to the data dictionary.
- Modified script `demo_obj_det.py` to demonstrate single frame as well as multi frame inference scenarios. Also added support to load other object detection datasets.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/392)

### CODE REVIEW

**Comment by ajinkyakhoche** [comment]
The visualization of predicted v/s GT boxes can be improved if we color them according to their confidence. For eg. GT boxes have confidence of -1.0 and can be colored green, and predictions as red, as shown in fig: 

image
 

Incidentally, I made such [a commit](https://github.com/isl-org/Open3D-ML/pull/366/commits/3b19eebd94eb29f841b539820ea6e0a732c7528d) in another pull request (#366 ) to dev branch. Shall I remove it from there and put it here?

**Review by sanskar107 — APPROVED** [review]
LGTM

**Comment by sanskar107** [comment]
@errissa this looks good to me. Could you also take a look on visualiser related changes ?

**Comment by errissa** [comment]
@sanskar107 looks good to me!

**Review by errissa — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/392)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ajinkyakhoche)

**Comment by sanskar107** [comment]
@ajinkyakhoche Thanks for your contribution. This looks good except that the fact that it merges to `master`. Could you please reopen this PR pointing to `dev` branch ? Thanks

**Comment by sanskar107** [comment]
Created another PR #431 to resolve conflicts and to merge to dev.

**Pull request closed without merging**
