### PR TITLE
Restructure Augmentation class.

### PR DESCRIPTION
**Pull request by sanskar107**
1.) Refactoring of augmentation class.
2) Added docstrings.
3) Error handling for augmentation methods.
4) Only using numpy RNG for augmentation.
5) Using same argument names as used in PyTorch. Added conversion mechanism for tensorflow. The list is small, and will be improved in future PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/294)

### CODE REVIEW

**Review by ssheorey — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d-ml/294)* status: all files reviewed, 10 unresolved discussions (waiting on @sanskar107)

___
*[ml3d/datasets/augment/augmentation.py, line 16 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/294#-MbnTsFf4f2cfky2vjX0:-MbnTsFf4f2cfky2vjX1:b-kr3y97) ([raw file](https://github.com/intel-isl/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L16)):*
> ```
> Recenter pointcloud/features to origin.
> ```
___
*[ml3d/datasets/augment/augmentation.py, line 73 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/294#-MbnTgqJ-kzVTY-C1dFy:-MbnTgqJ-kzVTY-C1dFz:b-vkal53) ([raw file](https://github.com/intel-isl/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L73)):*
> ```Python
>         if np.abs(pc[:, :3].mean()) > 1e-2:
>             warnings.warn(
>                 f"It is recommended recenter the pointcloud before calling rotate."
> ```

typo: recommended to recenter
___
*[ml3d/datasets/augment/augmentation.py, line 118 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/294#-MbnU4Zn1zwsW_qJHkn2:-MbnU4Zn1zwsW_qJHkn3:b-m4acj8) ([raw file](https://github.com/intel-isl/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L118)):*
> ```
> same scale  from range [`max_s`, `min_s`) is applied to each point.
> ```
(half-open interval from np.random.rand output)
___
*[ml3d/datasets/augment/augmentation.py, line 144 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/294#-MbnXnIp2FizDXTLCLbg:-MbnXnIp2FizDXTLCLbh:b8mq330) ([raw file](https://github.com/intel-isl/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L144)):*
> ```Python
> 
>         return pc + noise
> ```

Do we want an `augment()` method for the base class as well? This will let us use these augmentations directly without going through one of the child classes. If not, we should have a placeholder function here with an error message pointing users to the child classes.
___
*[ml3d/datasets/augment/augmentation.py, line 147 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/294#-MbnUgcs4_K3pqDVYt2k:-MbnUgcs4_K3pqDVYt2l:bbxpdmq) ([raw file](https://github.com/intel-isl/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L147)):*
> ```
> consisting of different
> ```
___
*[ml3d/datasets/augment/augmentation.py, line 164 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/294#-MbnUlml9PqUbpF7v_5f:-MbnUlml9PqUbpF7v_5g:b-1iilrd) ([raw file](https://github.com/intel-isl/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L164)):*
> ```
> configuraiton
> ```
spelling
___
*[ml3d/datasets/augment/augmentation.py, line 253 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/294#-Mbn_xTg5gaevOa-e5Sb:-Mbn_xTg5gaevOa-e5Sc:b-2zkp99) ([raw file](https://github.com/intel-isl/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L253)):*
> ```Python
>         return feats
> 
>     def augment(self, point, feat, labels, cfg):
> ```

Add error checking (warnings) for unimplemented or mis-spelled augmentation names in cfg.
___
*[ml3d/datasets/augment/augmentation.py, line 332 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/294#-MbnVYnjCdO5zk5FN6yA:-MbnVYnjCdO5zk5FN6yB:bstmj1y) ([raw file](https://github.com/intel-isl/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L332)):*
> ```
> data: Input data dict with keys ('point', 'bounding_boxes', 'calib')
> ```
Also mention required keys in dicts below.
___
*[ml3d/datasets/augment/augmentation.py, line 381 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/294#-MbnW-_d8g3YLtdjUas2:-MbnW-_eDvVYpZitsxoH:b4hi15f) ([raw file](https://github.com/intel-isl/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L381)):*
> ```Python
>         Args:
>             pickle_path: Path of pickle file generated using `scripts/collect_bbox.py`.
>             min_points_dict: A dictionary to filter objects based on number of points inside.
> ```

State keys required in dicts (i.e. format of this input argument)
___
*[ml3d/datasets/augment/augmentation.py, line 415 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/294#-MbnWNsQ48B60B4wFBsZ:-MbnWNsR-iRcn4MM1EGH:b-9j9vw4) ([raw file](https://github.com/intel-isl/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L415)):*
> ```Python
>             Augmented `data` dictionary.
> 
>         """
> ```

We need to process augmentations from the base class as well.
Add error checking (warnings) for unimplemented or mis-spelled augmentation names in cfg.

**Review by sanskar107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/294)* status: 12 of 13 files reviewed, 10 unresolved discussions (waiting on @ssheorey)

___
*[ml3d/datasets/augment/augmentation.py, line 16 at r1](https://reviewable.io/reviews/isl-org/open3d-ml/294#-MbnTsFf4f2cfky2vjX0:-MgB98T09triBoSn7NuX:b-896fix) ([raw file](https://github.com/isl-org/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L16)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> Recenter pointcloud/features to origin.
> ```

</blockquote></details>

Done.
___
*[ml3d/datasets/augment/augmentation.py, line 73 at r1](https://reviewable.io/reviews/isl-org/open3d-ml/294#-MbnTgqJ-kzVTY-C1dFy:-MgB998u3Ccq2YMHP66e:b-896fix) ([raw file](https://github.com/isl-org/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L73)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

typo: recommended to recenter
</blockquote></details>

Done.
___
*[ml3d/datasets/augment/augmentation.py, line 118 at r1](https://reviewable.io/reviews/isl-org/open3d-ml/294#-MbnU4Zn1zwsW_qJHkn2:-MgB99fWC8lu2GJapIks:b-896fix) ([raw file](https://github.com/isl-org/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L118)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> same scale  from range [`max_s`, `min_s`) is applied to each point.
> ```
(half-open interval from np.random.rand output)
</blockquote></details>

Done.
___
*[ml3d/datasets/augment/augmentation.py, line 144 at r1](https://reviewable.io/reviews/isl-org/open3d-ml/294#-MbnXnIp2FizDXTLCLbg:-MgB9BOBEahkKyymRhxj:b-896fix) ([raw file](https://github.com/isl-org/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L144)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Do we want an `augment()` method for the base class as well? This will let us use these augmentations directly without going through one of the child classes. If not, we should have a placeholder function here with an error message pointing users to the child classes.
</blockquote></details>

Done.
___
*[ml3d/datasets/augment/augmentation.py, line 147 at r1](https://reviewable.io/reviews/isl-org/open3d-ml/294#-MbnUgcs4_K3pqDVYt2k:-MgB9Boz4MW2F_9F9pJc:b-896fix) ([raw file](https://github.com/isl-org/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L147)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> consisting of different
> ```

</blockquote></details>

Done.
___
*[ml3d/datasets/augment/augmentation.py, line 164 at r1](https://reviewable.io/reviews/isl-org/open3d-ml/294#-MbnUlml9PqUbpF7v_5f:-MgB9CET8N0sWvsieZCU:b-896fix) ([raw file](https://github.com/isl-org/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L164)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> configuraiton
> ```
spelling
</blockquote></details>

Done.
___
*[ml3d/datasets/augment/augmentation.py, line 253 at r1](https://reviewable.io/reviews/isl-org/open3d-ml/294#-Mbn_xTg5gaevOa-e5Sb:-MgB9D2dDNXtE0qV2WD_:b99ekbu) ([raw file](https://github.com/isl-org/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L253)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add error checking (warnings) for unimplemented or mis-spelled augmentation names in cfg.
</blockquote></details>

Added in constructor.
___
*[ml3d/datasets/augment/augmentation.py, line 332 at r1](https://reviewable.io/reviews/isl-org/open3d-ml/294#-MbnVYnjCdO5zk5FN6yA:-MgB9Fgo9-UwdIwCn2LB:b-896fix) ([raw file](https://github.com/isl-org/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L332)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> data: Input data dict with keys ('point', 'bounding_boxes', 'calib')
> ```
Also mention required keys in dicts below.
</blockquote></details>

Done.
___
*[ml3d/datasets/augment/augmentation.py, line 381 at r1](https://reviewable.io/reviews/isl-org/open3d-ml/294#-MbnW-_d8g3YLtdjUas2:-MgB9GHfCb4DBWNkGTIW:b-896fix) ([raw file](https://github.com/isl-org/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L381)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

State keys required in dicts (i.e. format of this input argument)
</blockquote></details>

Done.
___
*[ml3d/datasets/augment/augmentation.py, line 415 at r1](https://reviewable.io/reviews/isl-org/open3d-ml/294#-MbnWNsQ48B60B4wFBsZ:-MgB9IVWDJeXN8QWjWfl:b-896fix) ([raw file](https://github.com/isl-org/open3d-ml/blob/da3893b85aac828d36552624b29c260f2594e142/ml3d/datasets/augment/augmentation.py#L415)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

We need to process augmentations from the base class as well.
Add error checking (warnings) for unimplemented or mis-spelled augmentation names in cfg.
</blockquote></details>

Done.

**Review by ssheorey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d-ml/294)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @ssheorey)

**Comment by ssheorey** [comment]
LGTM.
We can re-run the failing CI after merging the voxelize API PR.

**Pull request merged**
